### ISSUE TITLE
[Fixed]Chrome浏览器使用useImg无法在轨迹点回放时画图

### ISSUE THREAD

**Issue by Joker1995** [linghuam/Leaflet.TrackPlayBack#2]
Draw.js的函数_drawShip2需要做下修改:
var img = new Image();
img.src = this.shipOptions.imgUrl;
if (img.complete) {
    	this._ctx.save();
        this._ctx.translate(point.x, point.y);
        this._ctx.rotate(Math.PI / 180 * dir);
        this._ctx.drawImage(img, 0 - offset.x, 0 - offset.y, width, height);
        this._ctx.restore();
        return;
 }
img.onload = function () {
      this._ctx.save();
      this._ctx.translate(point.x, point.y);
      this._ctx.rotate(Math.PI / 180 * dir);
      this._ctx.drawImage(img, 0 - offset.x, 0 - offset.y, width, height);
      this._ctx.restore();
    }.bind(this);
原因暂时未知,可能不同浏览器对image的complete和onload方法支持不一样,之前的代码在IE Edge没问题

**Comment by linghuam** [comment]
谢谢，最近有空把整个代码做了一些优化，发现了这个问题，目前已经解决。
