### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by mengtingdin** [linghuam/Leaflet.TrackPlayBack#3]
![image](https://user-images.githubusercontent.com/26789523/50053821-2c267f80-0176-11e9-8950-67c0e815227b.png)，您好，运行npm run dev ,然后一直处于这个状态，需要等待么？不接受任何输入

**Comment by linghuam** [comment]
你好，这是一个lealet插件库，运行 npm run build 构建，构建生成的文件在 dist 文件夹中，将其引入项目即可使用。不知道你要 npm run dev 做什么用？

**Comment by mengtingdin** [comment]
好的，谢谢，已经解决了
